name: LimitedWorldEdit
softdepend: [WorldEdit,WorldGuard,Towny,PlotMe]
main: com.james137137.LimitedWorldEdit.LimitedWorldEdit
version: ${project.version}
authors: [James Anderson]
commands:
  DonatorsWorldEdit:
    description: DonatorsWorldEdit
permissions:
  LimitedWorldEdit.*:
    description: Gives access to all LimitedWorldEdit commands
    children:
      LimitedWorldEdit.bypass: true
  LimitedWorldEdit.bypass:
    description: Allows player to bypass LimitedWorldEdit
    default: op